spring:
# AOP 配置
  jmx:
      default-domain: account
  aop:
    proxy-target-class: true
# 数据源配置
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/hjs-smail?useSSL=false&characterEncoding=UTF-8
      url: jdbc:mysql://118.190.133.194:3306/hjs?useSSL=false&characterEncoding=UTF-8
      username: root
      password: JSH@#0629SDJU
      initial-size: 2
      max-active: 30
      min-idle: 2
      max-wait: 1234
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      validation-query: select 'x'
      validation-query-timeout: 1
      test-on-borrow: true
      test-while-idle: true
      test-on-return: true
      filters: stat, wall, slf4j
      aop-patterns: com.haojishi.mapper.*
      stat-view-servlet:
        login-username: wangqiang
        login-password: 123456123

# Thymeleaf
  thymeleaf:
    mode: HTML
    cache: false
#  http:
    multipart:
      max-file-size: 10MB

# js添加版本
  resources :
      chain :
        strategy :
          fixed :
            enabled: true
            paths: /js/**,/v1.0.0/**
            version: v1.0.0

mybatis:
    type-aliases-package: com.haojishi.model
    mapper-locations: classpath:com/haojishi/mapper/*.xml

mapper:
    mappers:
        - tk.mybatis.mapper.common.Mapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# 日志配置
logging:
  level:
    com.xzcysoft: debug
    org.springframework: error

api:
  #图片和视频存放路径
  fileImagePath: /var/tomcat/tomcat-8/webapps/image
  ImageSrc: http://118.24.109.190:443/image


  appid: wxb363c68215a1d3f1
  secret: 98e5dbf56fed8c9e0c5fb95f5d34ba05

